server:
  port: 5001
spring:
  application:
    name: alibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.111:8848

management:
  endpoint:
    web:
      exposure:
        include: '*'