server:
  port: 8803

spring:
  application:
    name: cloud-stream-rabbitmq-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          # ！=！=！实际这里可能会爆红，不用管，可以正常运行 ！=！=！
          binder: defaultRabbit  # 设置要绑定的消息服务的具体设置
          group: AtguiguA   #自定义分组

#eureka client 配置
eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进 eureka server 默认为true
    fetch-registry: true     #是否从 eureka server 抓取自己已有的注册信息默认为true,单节点无所谓,集群必须设置为true,才能配合 ribbon 使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka    #物业中心地址
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: consumer8803.com
    prefer-ip-address: true
    #eureka 客户端端向服务端发送心跳的时间间隔,单位为秒(默认30秒)
    lease-expiration-duration-in-seconds: 1
    #ureka 服务端在接收到最后一次心跳后等待时间上限,单位为秒(90秒),超时将剔除服务
    lease-renewal-interval-in-seconds: 2


