server:
  port: 3344


spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaoguangxiao/springcloud-config.git   #github的地址
      #搜索目录
          search-paths:
            - springcloud-config  #github仓库名
          skip-ssl-validation: true
        default-label: main





#eureka client 配置
eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进 eureka server 默认为true
    fetch-registry: true     #是否从 eureka server 抓取自己已有的注册信息默认为true,单节点无所谓,集群必须设置为true,才能配合 ribbon 使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka    #物业中心地址
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloud-config-center
    prefer-ip-address: true
    #eureka 客户端端向服务端发送心跳的时间间隔,单位为秒(默认30秒)
    lease-expiration-duration-in-seconds: 1
    #ureka 服务端在接收到最后一次心跳后等待时间上限,单位为秒(90秒),超时将剔除服务
    lease-renewal-interval-in-seconds: 2