server:
  port: 2002
spring:
  application:
    name: seata-stroage-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: qwe_tx_group
    nacos:
      discovery:
        server-addr: 192.168.247.111:8848

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.247.111:3306/seata_storage?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource


feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.seata.domain   #所有Entity别名类所在包
