server:
  port: 85

spring:
  application:
    name: cloud-consumer-feign-order85



#eureka client 配置

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进 eureka server 默认为true
    fetch-registry: true     #是否从 eureka server 抓取自己已有的注册信息默认为true,单节点无所谓,集群必须设置为true,才能配合 ribbon 使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka    #物业中心地址
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
#设置feign 客户端超时时间(openfeign 默认支持 ribbon)
ribbon:
  ReadTimeout: 5000 #指的是建立连接所用的时间,适用于网络状况正常情况下,两端连接所用的时间
  Connectimeout: 5000 #指的是建立连接后从服务器读取到可用资源的时间

logging:
  level:
    #feign 日志什么级别监控那些接口
    com.atguigu.springcloud.controller.OrderController: debug