server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway
    #gateway 配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能,利用微服务进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://CLOUD-PROVIDER-SERVICE
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PROVIDER-SERVICE
          filters:
            - AddRequestHeader=username, zgx
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            - After=2020-12-23T13:43:07.312+08:00[Asia/Shanghai]
            #- Before=2020-12-23T13:53:04.156+08:00[Asia/Shanghai]
            #- Between=2020-12-23T13:53:04.156+08:00[Asia/Shanghai], 2020-12-23T13:55:04.156+08:00[Asia/Shanghai]
            #- Cookie=username, root
            #- Header=X-Request-Id, 1234
            #- Host=**.atguigu.com
            #- Method=GET,POST
            #- Query=username,\d+  #要有参数名为username 并且值还是整数才能路由



#eureka client 配置
eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进 eureka server 默认为true
    fetch-registry: true     #是否从 eureka server 抓取自己已有的注册信息默认为true,单节点无所谓,集群必须设置为true,才能配合 ribbon 使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka    #物业中心地址
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloud-gateway-gateway
    prefer-ip-address: true
    #eureka 客户端端向服务端发送心跳的时间间隔,单位为秒(默认30秒)
    lease-expiration-duration-in-seconds: 1
    #ureka 服务端在接收到最后一次心跳后等待时间上限,单位为秒(90秒),超时将剔除服务
    lease-renewal-interval-in-seconds: 2